server:
  port: 8081
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        hostname: ${SERVICE_HOST_NAME}
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
        bootstrap: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true