server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
    gateway:
      mvc:
        routes:
          - id: service-book
            predicates:
              - Path=/api/v1/books/**,/api/v1/authors/**,/api/v1/series/**,/api/v1/genres/**
            uri: lb://service-book
            filters:
              - CircuitBreaker=myCircuitBreaker
          - id: service-media
            predicates:
              - Path=/api/v1/media/**
            uri: lb://service-media
            filters:
              - CircuitBreaker=myCircuitBreaker
          - id: service-user
            predicates:
              - Path=/api/v1/users/**, /api/v1/signing, /api/v1/signup
            uri: lb://service-user
            filters:
              - CircuitBreaker=myCircuitBreaker
    config:
      discovery:
        enabled: true
        service-id: config
  config:
    import: optional:configserver:config
