spring:
  application:
    name: gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/book_project
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection.pool_size: 20
        jdbc.batch_size: 20
