spring:
  application:
    name: service-book
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/book_project
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection.pool_size: 20
        jdbc.batch_size: 20
        cache:
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
          use_second_level_cache: true
          jcache:
            config: ehcache.xml
server:
  port: 0
