spring:
  application:
    name: service-user
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection.pool_size: 20
        jdbc.batch_size: 20
        cache:
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
          use_second_level_cache: true
          jcache:
            config: ehcache.xml
  kafka:
    producer:
      bootstrap-servers: broker.default.svc.cluster.local:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: statistic
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true