apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: book_project-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "8500"
            - name: SERVICE_HOST_NAME
              value: "gateway.default.svc.cluster.local"
            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/book_project"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USER
              value: "postgres"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: gateway