apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-book
  labels:
    app: service-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-book
  template:
    metadata:
      name: service-book
      labels:
        app: service-book
    spec:
      containers:
        - name: service-book
          image: vladzinko/service-book
          imagePullPolicy: IfNotPresent
          env:
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "8500"
            - name: SERVICE_HOST_NAME
              value: "service-book.default.svc.cluster.local"
            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/book_project"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USER
              value: "postgres"
            - name: BOOTSTRAP_SERVERS
              value: "broker.default.svc.cluster.local:29092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-book
spec:
  selector:
    app: service-book
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: service-book