server:
  port: 0
spring:
  application:
    name: service-user
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
  config:
    import: optional:configserver:config