server:
  port: 8080
spring:
  application:
    name: service-user
  cloud:
    consul:
      discovery:
        enabled: true
        hostname: ${SERVICE_HOST_NAME}
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}

    config:
      discovery:
        enabled: true
        service-id: config
  config:
    import: optional:configserver:config

